<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\query\RequestQuery;

/**
 * This is the base-model class for table "request".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property string $leave_date
 * @property string $leave_reason
 * @property integer $request_status_id
 * @property integer $hr_id
 * @property string $deleted_at
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Employee $employee
 * @property \app\models\RequestStatus $requestStatus
 */
abstract class Request extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'request';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['employee_id', 'request_status_id', 'hr_id'], 'integer'],
            [['leave_date', 'deleted_at'], 'safe'],
            [['leave_reason'], 'string'],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::class, 'targetAttribute' => ['employee_id' => 'id']],
            [['request_status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\RequestStatus::class, 'targetAttribute' => ['request_status_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'employee_id' => 'Employee ID',
            'leave_date' => 'Leave Date',
            'leave_reason' => 'Leave Reason',
            'request_status_id' => 'Request Status ID',
            'hr_id' => 'Hr ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::class, ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestStatus()
    {
        return $this->hasOne(\app\models\RequestStatus::class, ['id' => 'request_status_id']);
    }

    /**
     * @inheritdoc
     * @return RequestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RequestQuery(static::class);
    }
}
